server:
  port: 8085
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/togaform?useUnicode=true&characterEncoding=utf8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java
      additional-exclude: WEB-INF/**
  freemarker:
    cache: false

mybatis:
  type-aliases-package: tgkt.togaform
  mapper-locations: classpath:mapper/*Mapper.xml